[font]
size = 13.0

[font.bold]
family = "Zed Mono Extended"
style  = "Bold"

[font.bold_italic]
family = "Zed Mono Extended"
style  = "Bold Italic"

[font.italic]
family = "Zed Mono Extended"
style  = "Italic"

[font.normal]
family = "Zed Mono Extended"
style  = "Regular"

[window]
padding = { x = 8, y = 1 }
opacity = 0.85

[colors.primary]
background = '#0E1113'
foreground = '#E8C597'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
