[font]
size = 13.0
normal.family = "ZedMono Nerd Font"
bold.family = "ZedMono Nerd Font"
italic.family = "ZedMono Nerd Font"
bold_italic.family = "ZedMono Nerd Font"

[window]
padding = { x = 8, y = 1 }
opacity = 0.76

[colors.primary]
background = '#282828'
foreground = '#E8C597'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
