[font]
size = 13.0

[font.bold]
family = "Zed Mono Extended"
style  = "Bold"

[font.bold_italic]
family = "Zed Mono Extended"
style  = "Bold Italic"

[font.italic]
family = "Zed Mono Extended"
style  = "Italic"

[font.normal]
family = "Zed Mono Extended"
style  = "Regular"

[window]
padding = { x = 8, y = 1 }
opacity = 0.85

[colors.primary]
background = '#000000'
foreground = '#dfbf8e'
