[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
size = 12.0
normal.family = "ZedMono Nerd Font"
bold.family = "ZedMono Nerd Font"
italic.family = "ZedMono Nerd Font"
bold_italic.family = "ZedMono Nerd Font"

[window]
padding = { x = 8, y = 1 }
opacity = 0.85

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
