# fcitx5 candidate window.


Vertical Candidate List=False
WheelForPaging=True
# needs CJK coverage, ZedMono has none
Font="Noto Sans CJK JP 11"
MenuFont="ZedMono Nerd Font 10"
TrayFont="ZedMono Nerd Font 10"
TrayOutlineColor=#282828
TrayTextColor=#ebdbb2
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLangaugeToDisplayText=True
Theme=gruvbox
DarkTheme=gruvbox
UseDarkTheme=False
UseAccentColor=False
PerScreenDPI=True
ForceWaylandDPI=0
EnableFractionalScale=True
