# Rose Pine theme for btop
# https://rosepinetheme.com

theme[main_bg]="#191724"
theme[main_fg]="#e0def4"
theme[title]="#e0def4"
theme[hi_fg]="#eb6f92"
theme[selected_bg]="#26233a"
theme[selected_fg]="#c4a7e7"
theme[inactive_fg]="#6e6a86"
theme[graph_text]="#908caa"
theme[proc_misc]="#9ccfd8"
theme[cpu_box]="#6e6a86"
theme[mem_box]="#6e6a86"
theme[net_box]="#6e6a86"
theme[proc_box]="#6e6a86"
theme[div_line]="#6e6a86"

theme[temp_start]="#31748f"
theme[temp_mid]="#f6c177"
theme[temp_end]="#eb6f92"

theme[cpu_start]="#9ccfd8"
theme[cpu_mid]="#f6c177"
theme[cpu_end]="#eb6f92"

theme[free_start]="#eb6f92"
theme[free_mid]="#f6c177"
theme[free_end]="#9ccfd8"

theme[cached_start]="#31748f"
theme[cached_mid]="#9ccfd8"
theme[cached_end]="#c4a7e7"

theme[available_start]="#eb6f92"
theme[available_mid]="#f6c177"
theme[available_end]="#9ccfd8"

theme[used_start]="#9ccfd8"
theme[used_mid]="#f6c177"
theme[used_end]="#eb6f92"

theme[download_start]="#31748f"
theme[download_mid]="#9ccfd8"
theme[download_end]="#c4a7e7"

theme[upload_start]="#eb6f92"
theme[upload_mid]="#ebbcba"
theme[upload_end]="#f6c177"

theme[process_start]="#9ccfd8"
theme[process_mid]="#f6c177"
theme[process_end]="#eb6f92"
